name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: azure-functions-postgres
  JAVA_VERSION: '11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: 'Build with Maven'
      run: mvn clean package

    - name: 'Run Tests'
      run: mvn test

    - name: 'Azure CLI Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions with Maven'
      run: |
        mvn azure-functions:deploy \
          -DfunctionAppName=${{ env.AZURE_FUNCTIONAPP_NAME }} \
          -DresourceGroup=azure-functions-rg \
          -Dazure.functions.maven.plugin.version=1.18.0
