name: Build and deploy Java project to Azure Function App - venkat-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: venkat-func
  JAVA_VERSION: '11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build with Maven
        run: mvn clean package

      - name: Package Azure Function App
        run: mvn azure-functions:package

      - name: Show package contents (debugging)
        run: ls -la target/azure-functions/${{ env.AZURE_FUNCTIONAPP_NAME }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: target/azure-functions/${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_11AD4101082542F8995BD50F7BA3FBE5 }}
          respect-pom-xml: true
          scm-do-build-during-deployment: false
          enable-oryx-build: false
