name: Build and deploy Java project to Azure Function App - venkat-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: venkat-func
  JAVA_VERSION: '11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build with Maven
        run: |
          mvn clean package
          # Verify Azure Functions package structure
          ls -lR target/azure-functions/${{ env.AZURE_FUNCTIONAPP_NAME }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: target/azure-functions/${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_11AD4101082542F8995BD50F7BA3FBE5 }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
          respect-pom-xml: false  # Required for Flex Consumption plans
          respect-funcignore: true

      - name: Verify deployment
        run: |
          echo "Function URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/PostgresExample"
          curl -s https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/PostgresExample
